name: Publish

# Controls when the workflow will run
on:
  push:
    tags:
      - "r-*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # re-assemble bob_build directory from the latest release
      - uses: robinraju/release-downloader@v1
        continue-on-error: true
        with:
          latest: true
          fileName: '*.tar.xz'

      - uses: robinraju/release-downloader@v1
        continue-on-error: true
        with:
          latest: true
          fileName: 'buildinfo.toml'

      - name: Extract archives
        if: ${{ hashFiles('*.tar.xz') != '' }}
        continue-on-error: true
        run: |
          mkdir -p bob_build
          for file in *.tar.xz; do tar --transform 's|^[^/]*|bob_build|' -xf "$file"; done
          mv buildinfo.toml bob_build/
          echo "yes" > had_prev

      - name: Copy old botpack
        if: ${{ hashFiles('had_prev') != '' }}
        run: cp -r bob_build bob_build_old

      - name: Split old platforms
        if: ${{ hashFiles('had_prev') != '' }}
        run: ./bob split bob_build_old

      - name: Build
        run: ./bob build bob.toml

      - name: Split new platforms
        run: ./bob split bob_build

      - name: Compress full botpack
        run: |
          tar cf - bob_build_x86_64-windows | xz -9 > botpack_x86_64-windows.tar.xz
          tar cf - bob_build_x86_64-linux | xz -9 > botpack_x86_64-linux.tar.xz

      - name: Generate platform diffs
        if: ${{ hashFiles('had_prev') != '' }}
        run: |
          ./bob diff bob_build_old_x86_64-windows bob_build_x86_64-windows > patch_x86_64-windows.bobdiff
          ./bob diff bob_build_old_x86_64-linux bob_build_x86_64-linux > patch_x86_64-linux.bobdiff

      - name: Compress botpack diffs
        if: ${{ hashFiles('had_prev') != '' }}
        run: |
          xz -9 patch_x86_64-windows.bobdiff
          xz -9 patch_x86_64-linux.bobdiff

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            botpack_*.tar.xz
            patch_*.bobdiff.xz
            bob_build/buildinfo.toml
          body: 'Pre-built binaries of various bots'
