# This is a basic workflow to help you get started with Actions
name: Publish

# Controls when the workflow will run
on:
  push:
    tags:
      - "*-*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # re-assemble bob_build directory from the latest release
      - uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*-full.tar.xz'
          out-file-path: 'bob_build'
          extract: true

      - name: Save old build info
        run: cp bob_build/buildinfo.toml buildinfo.toml

      - name: Build
        run: ./bob build bob.toml

      - name: Package
        run: ./bob pack --old-buildinfo buildinfo.toml

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: ./bob_build/*.tar.xz
          body: 'Pre-built binaries of various bots'
