name: Publish

# Controls when the workflow will run
on:
  push:
    tags:
      - "r-*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Docker caching
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('bob') }}

      # re-assemble bob_build directory from the latest release
      - uses: robinraju/release-downloader@v1
        continue-on-error: true
        with:
          latest: true
          fileName: '*.tar.xz'

      - name: Extract archives
        if: ${{ hashFiles('*.tar.xz') != '' }}
        run: mkdir -p bob_build && for file in *.tar.xz; do tar -xf "$file" -C bob_build; done

      - name: Copy old botpack
        if: ${{ hashFiles('*.tar.xz') != '' }}
        run: cp -r bob_build bob_build_old

      - name: Build
        run: ./bob build bob.toml

      - name: Split platforms
        run: |
          ./bob split bob_build_old
          ./bob split bob_build

      - name: Generate platform diffs
        run: |
          ./bob diff bob_build_old_x86_64-windows bob_build_x86_64-windows > patch_x86_64-windows.bobdiff
          ./bob diff bob_build_old_x86_64-linux bob_build_x86_64-linux > patch_x86_64-linux.bobdiff

      - name: Compress full botpack
        run: |
          tar cf - bob_build_x86_64-windows | xz -9 > botpack_x86_64-windows.tar.xz
          tar cf - bob_build_x86_64-linux | xz -9 > botpack_x86_64-linux.tar.xz

      - name: Compress botpack diffs
        run: |
          xz -9 patch_x86_64-windows.bobdiff
          xz -9 patch_x86_64-linux.bobdiff

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            botpack_*.tar.xz
            patch_*.bobdiff.xz
          body: 'Pre-built binaries of various bots'
